import { type Law } from "@shared/schema";

// Helper function to ensure all laws have required fields
const ensureCompleteData = (law: Partial<Law>): Law => ({
  modernExample: "Modern applications of this law can be seen in contemporary business and social situations.",
  psychologyBehind: "This law leverages fundamental aspects of human psychology and behavior patterns.",
  practicalApplication: "Apply this law thoughtfully in professional and personal situations for maximum effectiveness.",
  commonMistakes: ["Applying the law too obviously", "Not understanding the context", "Overusing the technique"],
  relatedConcepts: ["Strategic thinking", "Social dynamics", "Power dynamics"],
  ...law,
} as Law);

const rawLawsData = [
  {
    id: 1,
    title: "Never Outshine the Master",
    shortDescription: "Always make those above you feel comfortably superior. Hide the extent of your own talents, as this might otherwise threaten their position.",
    fullDescription: "Always make those above you feel comfortably superior. In your desire to please or impress them, do not go too far in displaying your talents or you might accomplish the opposite—inspire fear and insecurity. Make your masters appear more brilliant than they are and you will attain the heights of power. This law applies to all relationships where there is a power imbalance, from workplace hierarchies to social dynamics.",
    principle: "Everyone has insecurities. When you show yourself in the presence of a person in power to be more intelligent, witty, or charming than they are, you are inadvertently making them feel that they are inferior. This is a dangerous feeling. Do not fool yourself into thinking that life has changed much since the days of Louis XIV and the court of Versailles. The human ego remains fragile, especially among those in positions of authority.",
    historicalExample: "Nicolas Fouquet, finance minister to Louis XIV, threw a lavish party at his château that outshone Versailles. The display of wealth and taste exceeded that of the king himself, leading to Fouquet's imprisonment and disgrace. The lesson: never make the mistake of thinking that you are irreplaceable. Fouquet's downfall came not from corruption or incompetence, but from making his king feel inferior through superior taste and wealth.",
    modernExample: "Consider the corporate executive who constantly showcases their intelligence in meetings with their CEO, correcting facts and presenting superior solutions. While their competence is undeniable, they often find themselves passed over for promotions or eventually pushed out. Meanwhile, the executive who subtly presents their boss's ideas as brilliant innovations while implementing their own strategic vision behind the scenes rises steadily through the ranks.",
    psychologyBehind: "This law exploits the fundamental human need for validation and superiority. People in power are especially vulnerable because their position makes them constant targets for comparison. When subordinates outshine them, it triggers deep-seated fears about competence and legitimacy. The psychological principle of 'narcissistic injury' explains why even well-intentioned displays of superiority can provoke disproportionate retaliation.",
    practicalApplication: "In practice, this means presenting your ideas as refinements or extensions of your superior's thoughts. Give credit generously while subtly taking responsibility for execution. In presentations, highlight how your boss's vision enabled your success. Ask for their advice even when you know the answer. Make them look good in front of their peers by praising their leadership publicly.",
    commonMistakes: [
      "Showing off technical expertise in front of your boss's peers",
      "Correcting your superior in public settings",
      "Taking full credit for successful projects",
      "Displaying superior social connections or lifestyle",
      "Being too eager to demonstrate your intelligence"
    ],
    keyPoints: ["Display your talents subtly", "Make superiors feel secure", "Avoid threatening their position", "Enhance their reputation", "Give credit while taking responsibility"],
    relatedConcepts: ["Emotional intelligence", "Strategic deference", "Ego management", "Political navigation"],
    category: "Strategy",
    icon: "crown"
  },
  {
    id: 2,
    title: "Never Put Too Much Trust in Friends, Learn How to Use Enemies",
    shortDescription: "Friends will betray you more quickly, for they are easily aroused to envy. But hire a former enemy and he will be more loyal than a friend.",
    fullDescription: "Be wary of friends—they will betray you more quickly, for they are easily aroused to envy. They also become spoiled and tyrannical. But hire a former enemy and he will be more loyal than a friend, because he has more to prove. In fact, you have more to fear from friends than from enemies. The person who was once your enemy has something to prove and will go to great lengths to show their loyalty.",
    principle: "A friend knows more about you than an enemy. But because you know each other so well, a friend becomes suspicious of your motives, expecting more and more from you. An enemy expects nothing, so when you win them over they are truly grateful. Friends often feel entitled to your success and may sabotage you when they feel left behind.",
    historicalExample: "Abraham Lincoln appointed several of his former political rivals to his cabinet, including Edwin Stanton as Secretary of War, who had publicly humiliated Lincoln years earlier. These former enemies became some of Lincoln's most loyal and effective cabinet members, while some of his longtime friends and supporters caused him the most political trouble.",
    modernExample: "Steve Jobs famously hired John Sculley from Pepsi, a former competitor, who initially helped Apple tremendously because he had everything to prove in a new industry. Conversely, many startups are destroyed not by external competition but by co-founders and early friends who become resentful when the company succeeds beyond their initial expectations.",
    psychologyBehind: "Friends operate on the principle of familiarity and entitlement, while former enemies operate on gratitude and the need to prove themselves. The psychological concept of 'earned loyalty' suggests that people value most what they've had to work for. Friends may take your success for granted, while converted enemies see it as validation of their decision to join you.",
    practicalApplication: "In business, consider hiring talented people from competitor companies who respect your vision. In politics, build coalitions by converting critics rather than just preaching to supporters. However, verify their conversion through small tests before entrusting them with critical responsibilities. Always maintain a balance—don't alienate all friends, but don't rely solely on them either.",
    commonMistakes: [
      "Assuming friendship guarantees loyalty",
      "Sharing all secrets with close friends",
      "Excluding former enemies permanently",
      "Not testing the loyalty of converted enemies",
      "Taking friends' support for granted"
    ],
    keyPoints: ["Friends can become envious easily", "Former enemies have more to prove", "Enemies expect nothing so gratitude runs deeper", "Test loyalty through actions", "Balance between friends and converted enemies"],
    relatedConcepts: ["Trust management", "Strategic alliances", "Loyalty psychology", "Coalition building"],
    category: "Defense",
    icon: "shield-alt"
  },
  {
    id: 3,
    title: "Conceal Your Intentions",
    shortDescription: "Keep people off-balance and in the dark by never revealing the purpose behind your actions. Lead them astray with false information.",
    fullDescription: "Keep people off-balance and in the dark by never revealing the purpose behind your actions. If they have no clue what you are up to, they cannot prepare a defense. Guide them far enough down the wrong path, envelop them in enough smoke, and by the time they realize your intentions, it will be too late. The key is to give people just enough information to think they understand your motives while your real plans remain hidden.",
    principle: "Humans are creatures of habit with an insatiable need to see patterns in the actions and events around them. Your predictability gives them a sense of control. Turn the tables: Be deliberately unpredictable. Behavior that seems to have no consistency or purpose will keep them off-balance. When people cannot predict your moves, they cannot effectively counter them.",
    historicalExample: "Otto von Bismarck masterfully concealed his intentions during the unification of Germany, making allies believe they were pursuing their own interests while actually serving his grand design. He would publicly advocate for peace while secretly preparing for war, making temporary alliances that he planned to break once they served their purpose.",
    modernExample: "Tech companies like Apple excel at this law by creating elaborate secrecy around product launches while deliberately leaking false information to competitors. Meanwhile, their actual innovations remain completely hidden until the dramatic reveal, preventing competitors from preparing adequate responses.",
    psychologyBehind: "This law leverages humans' pattern-recognition instincts and their tendency to fill information gaps with assumptions. When people encounter ambiguous behavior, they create explanations that often reveal more about their own intentions than yours. The uncertainty creates anxiety, making them more likely to make mistakes or reveal their own strategies while trying to understand yours.",
    practicalApplication: "In negotiations, never reveal your true bottom line or timeline pressures. In business, pursue multiple apparent strategies while secretly developing your real advantage. Share information selectively, ensuring different parties have different pieces of the puzzle. Use red herrings—visible but ultimately unimportant activities that misdirect attention from your true focus.",
    commonMistakes: [
      "Being too obvious about misdirection",
      "Revealing long-term plans to gain short-term trust",
      "Underestimating others' intelligence and observation skills",
      "Creating patterns in your deception that can be detected",
      "Confusing even your own team about real objectives"
    ],
    keyPoints: ["Use misdirection effectively", "Keep true motives hidden", "Create false patterns", "Maintain unpredictability", "Control information flow strategically"],
    relatedConcepts: ["Strategic ambiguity", "Information warfare", "Cognitive misdirection", "Competitive intelligence"],
    category: "Strategy",
    icon: "mask"
  },
  {
    id: 4,
    title: "Always Say Less Than Necessary",
    shortDescription: "When you are trying to impress people with words, the more you say, the more common you appear, and the less in control.",
    fullDescription: "When you are trying to impress people with words, the more you say, the more common you appear, and the less in control. Even if you are saying something banal, it will seem original if you make it vague, open-ended, and sphinxlike. Powerful people impress and intimidate by saying less. The ability to say nothing when nothing should be said is a mark of emotional intelligence and strategic thinking.",
    principle: "The more you say, the more likely you are to say something foolish. There is great power in silence. Learn to say less than necessary. Make others hang on your words and try to interpret their meaning. When words are scarce, they have much greater impact when finally spoken.",
    historicalExample: "When Louis XIV held court, he would often sit in complete silence, letting others fill the void with chatter. This made his eventual words carry tremendous weight and authority. His silence created an aura of wisdom and power that spoke volumes about his confidence and position.",
    modernExample: "Warren Buffett is famous for his measured speaking style and long pauses during interviews. His silence creates anticipation, and when he finally speaks, markets often move based on his words. In contrast, executives who constantly tweet or make public statements often diminish their authority through over-communication.",
    psychologyBehind: "Humans fill silence with their own projections and anxieties. When someone speaks less, others unconsciously attribute more wisdom and depth to them. The scarcity principle applies to words just as it does to goods—rare things are perceived as more valuable. Silence also forces others to reveal more about themselves as they try to fill the conversational void.",
    practicalApplication: "In negotiations, speak last and let others reveal their positions first. During conflicts, avoid defensive explanations that make you appear weak. In leadership, deliver key messages concisely and pause for effect. When receiving criticism, respond minimally until you've had time to process. Practice the art of the meaningful pause in presentations and conversations.",
    commonMistakes: [
      "Over-explaining your position when challenged",
      "Filling uncomfortable silences immediately",
      "Revealing your hand too early in negotiations",
      "Talking when you're emotional or angry",
      "Trying to impress others with your knowledge"
    ],
    keyPoints: ["Silence creates mystery", "Less words carry more weight", "Avoid revealing too much", "Let others interpret your meaning", "Use strategic pauses for impact"],
    relatedConcepts: ["Strategic silence", "Scarcity principle", "Active listening", "Emotional regulation"],
    category: "Influence",
    icon: "comment-slash"
  },
  {
    id: 5,
    title: "So Much Depends on Reputation—Guard It with Your Life",
    shortDescription: "Reputation is the cornerstone of power. Through reputation alone you can intimidate and win; once it slips, you are vulnerable.",
    fullDescription: "Reputation is the cornerstone of power. Through reputation alone you can intimidate and win; once you slip, however, you are vulnerable, and will be attacked on all sides. Make your reputation unassailable. Always be alert to potential attacks and thwart them before they happen.",
    principle: "Your reputation inevitably precedes you, and if it inspires respect, a great deal of your work is done for you before you arrive on the scene. Your reputation for honesty and integrity is your most valuable asset.",
    historicalExample: "P.T. Barnum understood that reputation was everything in show business. Even negative publicity served his purposes as long as people were talking about him. He carefully crafted his reputation as the greatest showman, which became a self-fulfilling prophecy.",
    keyPoints: ["Reputation precedes you everywhere", "Protect against attacks on character", "Use reputation as a weapon", "Monitor what others say about you"],
    category: "Influence",
    icon: "chess-queen"
  },
  {
    id: 6,
    title: "Court Attention at All Costs",
    shortDescription: "Everything is judged by its appearance; what is unseen counts for nothing. Never let yourself get lost in the crowd.",
    fullDescription: "Everything is judged by its appearance; what is unseen counts for nothing. Never let yourself get lost in the crowd, then, or buried in oblivion. Stand out. Be conspicuous, at all costs. Make yourself a magnet of attention by appearing larger, more colorful, more mysterious than the bland and timid masses.",
    principle: "Better to be attacked, even slandered, than ignored. All professions are ruled by this law, and all professionals must have a bit of the charlatan. Attention, whether positive or negative, is the coin of the realm in the modern world.",
    historicalExample: "Madonna built her career on constantly reinventing herself and courting controversy. Each transformation generated massive media attention, keeping her relevant across decades in a notoriously fickle industry.",
    keyPoints: ["Visibility equals viability", "Stand out from the crowd", "Create memorable impressions", "Control the narrative around you"],
    category: "Influence",
    icon: "star"
  },
  {
    id: 7,
    title: "Get Others to Do the Work for You, but Always Take the Credit",
    shortDescription: "Use the wisdom, knowledge, and legwork of other people to further your own cause. Never do yourself what others can do for you.",
    fullDescription: "Use the wisdom, knowledge, and legwork of other people to further your own cause. Not only will such assistance save you valuable time and energy, it will give you a godlike aura of efficiency and speed. In the end your helpers will be forgotten and you will be remembered.",
    principle: "Your efficient use of the work and intelligence of others not only saves you effort but also demonstrates your skill in directing and commanding people. This is a critical leadership ability.",
    historicalExample: "Thomas Edison was known as a great inventor, but many of his 'inventions' were actually created by the talented team in his laboratory. Edison's genius lay in organizing talent and taking credit for the collective output.",
    keyPoints: ["Leverage others' expertise", "Save your energy for strategy", "Demonstrate leadership capability", "Ensure you get the recognition"],
    category: "Strategy",
    icon: "users"
  },
  {
    id: 8,
    title: "Make Other People Come to You—Use Bait if Necessary",
    shortDescription: "When you force the other person to act, you are the one in control. It is always better to make your opponent come to you.",
    fullDescription: "When you force the other person to act, you are the one in control. It is always better to make your opponent come to you, abandoning his own plans in the process. Lure him with fabulous gains—then attack. You hold the cards.",
    principle: "When you make others come to you, you create the illusion that they are in control when actually you are. They are walking into your territory, by your rules. You have the advantage of preparation and familiar ground.",
    historicalExample: "Napoleon often used tactical retreats to lure enemies into disadvantageous positions on terrain of his choosing. The enemy thought they were pursuing a weakened force, only to find themselves in carefully prepared traps.",
    keyPoints: ["Control the meeting ground", "Force opponents to react", "Use compelling bait", "Maintain strategic patience"],
    category: "Strategy",
    icon: "magnet"
  },
  {
    id: 9,
    title: "Win Through Your Actions, Never Through Argument",
    shortDescription: "Any momentary triumph you think gained through argument is really a Pyrrhic victory. The resentment and ill will you stir up is stronger than any temporary change of opinion.",
    fullDescription: "Any momentary triumph you think you have gained through argument is really a Pyrrhic victory: The resentment and ill will you stir up is stronger and lasts longer than any momentary change of opinion. It is much more powerful to get others to agree with you through your actions, without saying a word.",
    principle: "Demonstrations are more powerful than explanations. When you prove your point through action, you bypass the ego and pride that make people resist being told they're wrong.",
    historicalExample: "Benjamin Franklin won over his political opponents not through debate, but by demonstrating the practical benefits of his proposals. His actions spoke louder than any argument could.",
    keyPoints: ["Actions speak louder than words", "Avoid creating resentment", "Demonstrate rather than argue", "Let results convince others"],
    category: "Influence",
    icon: "check-circle"
  },
  {
    id: 10,
    title: "Infection: Avoid the Unhappy and Unlucky",
    shortDescription: "You can die from someone else's misery—emotional states are as infectious as disease. Avoid the chronically dissatisfied.",
    fullDescription: "You can die from someone else's misery—emotional states are as infectious as diseases. You may feel you are helping the drowning man but you are only precipitating your own disaster. The unfortunate sometimes draw misfortune on themselves; they will also draw it on you.",
    principle: "Emotional contagion is real and powerful. The people around you affect your mood, energy, and even your luck. Choose your associations carefully, as they will inevitably influence your own trajectory.",
    historicalExample: "The court of Louis XVI was filled with pessimistic nobles who had given up hope. Their defeatist attitude infected the entire royal circle, contributing to their collective downfall during the French Revolution.",
    keyPoints: ["Choose positive associations", "Emotional states are contagious", "Protect your mental energy", "Seek out successful people"],
    category: "Defense",
    icon: "virus"
  },
  {
    id: 11,
    title: "Learn to Keep People Dependent on You",
    shortDescription: "To maintain your independence you must always be needed and wanted. The more you are relied on, the more freedom you have.",
    fullDescription: "To maintain your independence you must always be needed and wanted. The more you are relied on, the more freedom you have. Make people depend on you for their happiness and prosperity and you have nothing to fear. Never teach them enough so that they can do without you.",
    principle: "Independence through dependence is paradoxical but powerful. When others need you, they cannot afford to lose you. This gives you tremendous leverage in any relationship or organization.",
    historicalExample: "Henry Kissinger made himself indispensable to multiple presidents by being the only one who fully understood the complex web of international relations he had helped create. His unique knowledge made him irreplaceable.",
    keyPoints: ["Become indispensable", "Control unique knowledge", "Create dependency", "Maintain your value"],
    category: "Strategy",
    icon: "link"
  },
  {
    id: 12,
    title: "Use Selective Honesty and Generosity to Disarm Your Victim",
    shortDescription: "One sincere and honest move will cover over dozens of dishonest ones. Open-hearted gestures of honesty and generosity bring down the guard of even the most suspicious people.",
    fullDescription: "One sincere and honest move will cover over dozens of dishonest ones. Open-hearted gestures of honesty and generosity bring down the guard of even the most suspicious people. Once your selective honesty opens a hole in their armor, you can deceive and manipulate them at will.",
    principle: "A single act of honesty is often worth more than a lifetime of lies because it is so rare and unexpected. Use this sparingly but effectively to gain trust when you need it most.",
    historicalExample: "The con artist Victor Lustig would begin his schemes with genuine acts of kindness and honesty, establishing trust before executing his elaborate deceptions. His early honesty made his later lies completely believable.",
    keyPoints: ["Strategic honesty builds trust", "Generosity lowers defenses", "Use sparingly for maximum effect", "Create contrast with your usual behavior"],
    category: "Strategy",
    icon: "gift"
  },
  {
    id: 13,
    title: "When Asking for Help, Appeal to People's Self-Interest",
    shortDescription: "If you need to turn to an ally for help, do not bother to remind him of your past assistance and good deeds. Instead, uncover something that will benefit him.",
    fullDescription: "If you need to turn to an ally for help, do not bother to remind him of your past assistance and good deeds. He will find a way to ignore you. Instead, uncover something in your request, or in your alliance with him, that will benefit him, and emphasize it out of all proportion.",
    principle: "People are fundamentally self-interested. When you align your requests with their personal benefits, you make it easy for them to say yes. This is not cynical—it's realistic and effective.",
    historicalExample: "When Benjamin Franklin wanted to win over a political opponent, he didn't appeal to their past friendship. Instead, he asked to borrow a rare book, making the man feel important and flattered. This simple request based on the man's self-image as a scholar won him over completely.",
    keyPoints: ["Focus on their benefits", "Ignore past favors", "Make requests easy to grant", "Appeal to their ego and interests"],
    category: "Influence",
    icon: "handshake"
  },
  {
    id: 14,
    title: "Pose as a Friend, Work as a Spy",
    shortDescription: "Knowing about your rival is critical. Use spies to gather valuable information that will keep you a step ahead.",
    fullDescription: "Knowing about your rival is critical. Use spies to gather valuable information that will keep you a step ahead. Better still: Play the spy yourself. In polite social encounters, learn to probe. Ask indirect questions to get people to reveal their weaknesses and intentions.",
    principle: "Information is power. The more you know about others' plans, weaknesses, and motivations, the better you can position yourself. Social situations are perfect for gathering intelligence.",
    historicalExample: "Talleyrand, the great French diplomat, was famous for his ability to extract information through seemingly casual conversation at social gatherings. He would learn state secrets at dinner parties that others couldn't discover through formal channels.",
    keyPoints: ["Gather information constantly", "Use social situations for intelligence", "Ask indirect questions", "Learn others' weaknesses and plans"],
    category: "Strategy",
    icon: "eye"
  },
  {
    id: 15,
    title: "Crush Your Enemy Totally",
    shortDescription: "All great leaders since Moses have known that a feared enemy must be crushed completely. Leave your enemies no options.",
    fullDescription: "All great leaders since Moses have known that a feared enemy must be crushed completely. (Sometimes they have learned this the hard way.) If you leave even one enemy alive, that enemy will seek revenge. Crush your enemy totally. In the end, this proves more merciful than leaving him half-alive.",
    principle: "A wounded enemy is more dangerous than a strong one because they have nothing left to lose. When you must act against an enemy, make sure they cannot recover or retaliate.",
    historicalExample: "Julius Caesar's mercy toward Brutus and other senators eventually led to his assassination. Had he completely eliminated the threat they posed, he might have lived to complete his transformation of Rome.",
    keyPoints: ["Eliminate threats completely", "Half-measures create vengeful enemies", "Wounded opponents are most dangerous", "Complete victory prevents future problems"],
    category: "Strategy",
    icon: "hammer"
  },
  {
    id: 16,
    title: "Use Absence to Increase Respect and Honor",
    shortDescription: "Too much circulation makes the price go down. The more you are seen and heard from, the more common you appear.",
    fullDescription: "Too much circulation makes the price go down: The more you are seen and heard from, the more common you appear. If you are already established in a group, temporary withdrawal from it will make you more talked about, even more admired. You must learn when to leave.",
    principle: "Scarcity creates value. When you withdraw strategically, people begin to idealize you and forget your flaws. Your absence will be felt more powerfully than your presence ever was.",
    historicalExample: "Greta Garbo's early retirement from films at the height of her career created a mystique that lasted decades. Her absence made her more legendary than continued acting ever could have.",
    keyPoints: ["Scarcity increases value", "Strategic withdrawal creates mystique", "People idealize what they can't have", "Know when to leave"],
    category: "Influence",
    icon: "eye-slash"
  },
  {
    id: 17,
    title: "Keep Others in Suspended Terror: Cultivate an Air of Unpredictability",
    shortDescription: "Humans are creatures of habit with an insatiable need to see patterns. Your predictability gives them a sense of control.",
    fullDescription: "Humans are creatures of habit with an insatiable need to see patterns in the actions and events around them. Your predictability gives them a sense of control. Turn the tables: Be deliberately unpredictable. Behavior that seems to have no consistency or purpose will keep them off-balance.",
    principle: "When people cannot predict your actions, they cannot prepare defenses against you. Controlled unpredictability can be a powerful tool for maintaining psychological advantage.",
    historicalExample: "Bobby Fischer's erratic behavior and unpredictable moves both in chess and in life kept his opponents constantly off-balance, never knowing what to expect next. This psychological warfare was part of his competitive advantage.",
    keyPoints: ["Break your own patterns", "Keep others guessing", "Use controlled chaos", "Maintain psychological advantage"],
    category: "Strategy",
    icon: "random"
  },
  {
    id: 18,
    title: "Do Not Build Fortresses to Protect Yourself—Isolation Is Dangerous",
    shortDescription: "The world is dangerous and enemies are everywhere—everyone has to protect themselves. A fortress seems the safest. But isolation exposes you to more dangers.",
    fullDescription: "The world is dangerous and enemies are everywhere—everyone has to protect themselves. A fortress seems the safest. But isolation exposes you to more dangers than it protects you from—it cuts you off from valuable information, it makes you conspicuous and an easy target.",
    principle: "Isolation may feel safe, but it actually makes you vulnerable. You need allies, information, and the ability to blend in. Fortresses can become prisons.",
    historicalExample: "Howard Hughes' increasing isolation in his later years made him paranoid and cut off from reality. His fortress mentality ultimately led to his downfall as he lost touch with his business empire and the outside world.",
    keyPoints: ["Isolation breeds paranoia", "Stay connected to information networks", "Blend in rather than stand apart", "Fortresses can become prisons"],
    category: "Defense",
    icon: "building"
  },
  {
    id: 19,
    title: "Know Who You're Dealing With—Do Not Offend the Wrong Person",
    shortDescription: "There are many different kinds of people in the world, and you can never assume that everyone will react to your strategies in the same way.",
    fullDescription: "There are many different kinds of people in the world, and you can never assume that everyone will react to your strategies in the same way. Deceive or outmaneuver some people and they will spend the rest of their lives seeking revenge. Choose your victims and opponents carefully.",
    principle: "Some people are more dangerous than others when crossed. Learn to identify personality types and adjust your approach accordingly. Some opponents will never forgive or forget.",
    historicalExample: "J. Edgar Hoover was known for keeping detailed files on everyone and never forgetting a slight. Many who crossed him early in their careers found themselves under FBI surveillance for decades afterward.",
    keyPoints: ["Study personality types", "Some people never forgive", "Choose your battles wisely", "Assess before you act"],
    category: "Defense",
    icon: "search"
  },
  {
    id: 20,
    title: "Do Not Commit to Anyone",
    shortDescription: "It is the fool who always rushes to take sides. Do not commit to any side or cause but yourself. By maintaining your independence, you become the master of others.",
    fullDescription: "It is the fool who always rushes to take sides. Do not commit to any side or cause but yourself. By maintaining your independence, you become the master of others—playing people against one another, making them pursue you. Stay aloof and you gain the power to intervene decisively when you choose.",
    principle: "Independence gives you options and leverage. When you commit too early or too completely, you lose flexibility and become vulnerable to the fortunes of others.",
    historicalExample: "Henry Kissinger maintained relationships with all sides during various international conflicts, never fully committing to any single alliance. This independence allowed him to broker deals that others couldn't.",
    keyPoints: ["Maintain independence", "Avoid premature commitments", "Keep your options open", "Use neutrality as leverage"],
    category: "Strategy",
    icon: "balance-scale"
  },
  {
    id: 21,
    title: "Play a Sucker to Catch a Sucker—Seem Dumber Than Your Mark",
    shortDescription: "No one likes feeling stupider than the next person. The trick is to make your victims feel smart—and not just smart, but smarter than you are.",
    fullDescription: "No one likes feeling stupider than the next person. The trick, then, is to make your victims feel smart—and not just smart, but smarter than you are. Once convinced of this, they will never suspect that you may have ulterior motives.",
    principle: "People's ego and pride make them vulnerable. When they think they're smarter than you, they lower their guard and become careless. Use this to your advantage.",
    historicalExample: "Socrates famously claimed to know nothing, which encouraged others to reveal their own ignorance while trying to educate him. This seeming humility was actually a powerful method of exposing others' weaknesses.",
    keyPoints: ["Let others feel superior", "Use apparent weakness as strength", "Pride makes people careless", "Hide your true intelligence"],
    category: "Strategy",
    icon: "theater-masks"
  },
  {
    id: 22,
    title: "Use the Surrender Tactic: Transform Weakness into Power",
    shortDescription: "When you are weaker, never fight for honor's sake; choose surrender instead. Surrender gives you time to recover, time to torment and irritate your conqueror.",
    fullDescription: "When you are weaker, never fight for honor's sake; choose surrender instead. Surrender gives you time to recover, time to torment and irritate your conqueror, time to wait for his power to wane. Do not give him the satisfaction of fighting and defeating you—surrender first.",
    principle: "Strategic surrender is not defeat—it's repositioning. Sometimes yielding gives you more power than fighting, especially when you're overmatched.",
    historicalExample: "When the Mongols conquered cities that surrendered immediately, they often spared them and incorporated local leaders into their administration. Cities that fought to the end were completely destroyed.",
    keyPoints: ["Strategic retreat preserves strength", "Live to fight another day", "Surrender can be a form of control", "Choose your battles carefully"],
    category: "Defense",
    icon: "flag-white"
  },
  {
    id: 23,
    title: "Concentrate Your Forces",
    shortDescription: "Conserve your forces and energies by keeping them concentrated at their strongest point. You gain more by finding a rich mine and mining it deeper.",
    fullDescription: "Conserve your forces and energies by keeping them concentrated at their strongest point. You gain more by finding a rich mine and mining it deeper, than by flitting from one shallow mine to another—intensity defeats extensity every time.",
    principle: "Focus creates power. Scattered efforts produce scattered results. Better to dominate one area completely than to be mediocre in many.",
    historicalExample: "Steve Jobs famously focused Apple on a small number of products, perfecting each one rather than competing across a broad range. This concentration of effort led to revolutionary products like the iPhone.",
    keyPoints: ["Focus creates intensity", "Depth beats breadth", "Concentrated effort yields better results", "Don't spread yourself too thin"],
    category: "Strategy",
    icon: "crosshairs"
  },
  {
    id: 24,
    title: "Play the Perfect Courtier",
    shortDescription: "The perfect courtier thrives in a world where everything revolves around power and political dexterity. Learn the art of indirection.",
    fullDescription: "The perfect courtier thrives in a world where everything revolves around power and political dexterity. He has mastered the art of indirection; he flatters, yields to superiors, and asserts power over others in the most oblique and graceful manner.",
    principle: "In any hierarchy, you must learn to navigate politics skillfully. Direct confrontation rarely works—subtle influence and careful positioning are more effective.",
    historicalExample: "Cardinal Richelieu served as the perfect courtier to Louis XIII, wielding enormous power behind the scenes through careful flattery, strategic alliances, and indirect influence over the king.",
    keyPoints: ["Master political navigation", "Use indirect influence", "Flatter superiors skillfully", "Assert power gracefully"],
    category: "Influence",
    icon: "crown"
  },
  {
    id: 25,
    title: "Re-Create Yourself",
    shortDescription: "Do not accept the roles that society foists on you. Re-create yourself by forging a new identity, one that commands attention and never bores the audience.",
    fullDescription: "Do not accept the roles that society foists on you. Re-create yourself by forging a new identity, one that commands attention and never bores the audience. Be the master of your own image rather than letting others define it for you.",
    principle: "You have the power to shape how others see you. Don't let circumstances or other people's expectations define your identity—take control of your personal brand.",
    historicalExample: "Madonna constantly reinvented her image throughout her career, never allowing herself to be pigeonholed. Each transformation kept her relevant and in control of her public persona.",
    keyPoints: ["Control your own narrative", "Don't accept others' definitions", "Reinvention prevents stagnation", "Master your image"],
    category: "Influence",
    icon: "palette"
  },
  {
    id: 26,
    title: "Keep Your Hands Clean",
    shortDescription: "You must seem a paragon of civility and efficiency: Your hands are never soiled by mistakes and nasty deeds.",
    fullDescription: "You must seem a paragon of civility and efficiency: Your hands are never soiled by mistakes and nasty deeds. Maintain such a spotless appearance by using others as scapegoats and cat's-paws to disguise your involvement.",
    principle: "Perception is reality in the court of public opinion. Always maintain plausible deniability and ensure that any negative consequences can be traced to others, not to you.",
    historicalExample: "Machiavelli advised princes to use intermediaries for unpleasant tasks so that the ruler's hands remained clean. If the intermediary failed or caused outrage, they could be sacrificed to protect the leader's reputation.",
    keyPoints: ["Maintain plausible deniability", "Use intermediaries for dirty work", "Protect your reputation", "Let others take the blame"],
    category: "Defense",
    icon: "hands-wash"
  },
  {
    id: 27,
    title: "Play on People's Need to Believe to Create a Cultlike Following",
    shortDescription: "People have an overwhelming desire to believe in something. Become the focal point of such desire by offering them a cause, a new faith to follow.",
    fullDescription: "People have an overwhelming desire to believe in something. Become the focal point of such desire by offering them a cause, a new faith to follow. Keep your words vague but full of promise; emphasize enthusiasm over rationality and clear thinking.",
    principle: "Humans have a fundamental need to belong to something greater than themselves. If you can position yourself as the leader of a movement or cause, people will follow you with surprising devotion.",
    historicalExample: "Steve Jobs created an almost religious devotion to Apple products by positioning the company as more than just a technology firm—it was a lifestyle, a belief system about thinking differently.",
    keyPoints: ["Tap into people's need to believe", "Create a compelling vision", "Use emotion over logic", "Build devoted followers"],
    category: "Influence",
    icon: "praying-hands"
  },
  {
    id: 28,
    title: "Enter Action with Boldness",
    shortDescription: "If you are unsure of a course of action, do not attempt it. Your doubts and hesitations will infect your execution.",
    fullDescription: "If you are unsure of a course of action, do not attempt it. Your doubts and hesitations will infect your execution. Timidity is dangerous: Better to enter with boldness. Any mistakes you commit through audacity are easily corrected with more audacity.",
    principle: "Confidence is contagious, and so is doubt. When you act boldly, others assume you know what you're doing and will follow your lead. Hesitation invites opposition.",
    historicalExample: "Alexander the Great's military successes came largely from his willingness to take bold, seemingly impossible actions that caught his enemies off guard. His confidence inspired his troops and intimidated his opponents.",
    keyPoints: ["Confidence inspires confidence", "Boldness overcomes obstacles", "Hesitation invites failure", "Audacity can correct mistakes"],
    category: "Strategy",
    icon: "rocket"
  },
  {
    id: 29,
    title: "Plan All the Way to the End",
    shortDescription: "The ending is everything. Plan all the way to it, taking into account all the possible consequences, obstacles, and twists of fortune.",
    fullDescription: "The ending is everything. Plan all the way to it, taking into account all the possible consequences, obstacles, and twists of fortune that might reverse your hard work and give the glory to others. By planning to the end you will not be overwhelmed by circumstances.",
    principle: "Most people plan only for the short term and are constantly surprised by consequences they didn't anticipate. Thinking through to the final outcome gives you a massive advantage.",
    historicalExample: "Chess grandmasters think many moves ahead, considering not just their immediate strategy but how the game will end. This long-term thinking allows them to set up victories from the opening moves.",
    keyPoints: ["Think through all consequences", "Plan for multiple scenarios", "Consider long-term outcomes", "Anticipate obstacles"],
    category: "Strategy",
    icon: "chess"
  },
  {
    id: 30,
    title: "Make Your Accomplishments Seem Effortless",
    shortDescription: "Your actions must seem natural and executed with ease. All the toil and practice that go into them, and also all the clever tricks, must be concealed.",
    fullDescription: "Your actions must seem natural and executed with ease. All the toil and practice that go into them, and also all the clever tricks, must be concealed. When you act, act effortlessly, as if you could do much more. Avoid the temptation of revealing how hard you work.",
    principle: "People are more impressed by natural talent than by hard work. If they see your effort, they'll think you're not naturally gifted. Hide your labor and let your results speak for themselves.",
    historicalExample: "Great performers like Fred Astaire made their incredibly difficult dance routines look effortless. The hours of practice and the physical pain were never visible to the audience, only the graceful result.",
    keyPoints: ["Hide your effort", "Make difficult look easy", "Natural talent impresses more", "Conceal your methods"],
    category: "Influence",
    icon: "feather"
  },
  {
    id: 31,
    title: "Control the Options: Get Others to Play with the Cards You Deal",
    shortDescription: "The best deceptions are the ones that seem to give the other person a choice: Your victims feel they are in control, but are actually your puppets.",
    fullDescription: "The best deceptions are the ones that seem to give the other person a choice: Your victims feel they are in control, but are actually your puppets. Give people options that come out in your favor whichever one they choose.",
    principle: "True control means setting up situations where all the available choices lead to your desired outcome. Let others think they're deciding while you shape their options.",
    historicalExample: "Henry Ford famously said customers could have any color car they wanted, as long as it was black. He gave the illusion of choice while maintaining complete control over his manufacturing process.",
    keyPoints: ["Shape available choices", "Create win-win situations for yourself", "Let others feel in control", "All roads lead to your goal"],
    category: "Strategy",
    icon: "cards"
  },
  {
    id: 32,
    title: "Play to People's Fantasies",
    shortDescription: "The truth is often avoided because it is ugly and unpleasant. Never appeal to truth and reality unless you are prepared for the anger that comes from disenchantment.",
    fullDescription: "The truth is often avoided because it is ugly and unpleasant. Never appeal to truth and reality unless you are prepared for the anger that comes from disenchantment. Life is so harsh and distressing that people who can manufacture romance or conjure up fantasy are like oases in the desert.",
    principle: "People prefer beautiful lies to ugly truths. If you can create compelling fantasies that make people feel good about themselves and their prospects, they will follow you anywhere.",
    historicalExample: "Disney built an empire by creating fantasy worlds that allowed people to escape from reality. The company understood that people will pay premium prices for experiences that make them feel magical and special.",
    keyPoints: ["People prefer fantasy to reality", "Create compelling visions", "Appeal to emotions over facts", "Make people feel special"],
    category: "Influence",
    icon: "magic"
  },
  {
    id: 33,
    title: "Discover Each Man's Thumbscrew",
    shortDescription: "Everyone has a weakness, a gap in the castle wall. That weakness is usually an insecurity, an uncontrollable emotion or need.",
    fullDescription: "Everyone has a weakness, a gap in the castle wall. That weakness is usually an insecurity, an uncontrollable emotion or need; it can also be a small secret pleasure. Either way, once found, it is a thumbscrew you can turn to your advantage.",
    principle: "Every person has a psychological vulnerability that can be exploited. The key is to identify what motivates them most deeply—their fears, desires, or insecurities.",
    historicalExample: "Legendary negotiator Henry Kissinger was masterful at identifying what each world leader wanted most and then structuring deals around those core desires, whether it was security, prestige, or legacy.",
    keyPoints: ["Everyone has weaknesses", "Identify core motivations", "Use psychology not force", "Find the emotional leverage point"],
    category: "Strategy",
    icon: "key"
  },
  {
    id: 34,
    title: "Be Royal in Your Own Fashion: Act Like a King to Be Treated Like One",
    shortDescription: "The way you carry yourself will often determine how you are treated: In the long run, appearing vulgar or common will make people disrespect you.",
    fullDescription: "The way you carry yourself will often determine how you are treated: In the long run, appearing vulgar or common will make people disrespect you. For a king respects himself and inspires the same sentiment in others. By acting regally and confident of your powers, you make yourself seem destined to wear a crown.",
    principle: "How you see yourself affects how others see you. If you behave as if you deserve respect and success, others will tend to treat you accordingly. Confidence and dignity are self-fulfilling prophecies.",
    historicalExample: "Coco Chanel came from poverty but carried herself with such elegance and confidence that she was accepted into high society. Her regal bearing convinced others that she belonged among the elite.",
    keyPoints: ["Confidence attracts respect", "Behave as you wish to be treated", "Dignity is magnetic", "Create your own nobility"],
    category: "Influence",
    icon: "crown"
  },
  {
    id: 35,
    title: "Master the Art of Timing",
    shortDescription: "Never seem to be in a hurry—hurrying betrays a lack of control over yourself, and over time. Always seem patient, as if you know that everything will come to you eventually.",
    fullDescription: "Never seem to be in a hurry—hurrying betrays a lack of control over yourself, and over time. Always seem patient, as if you know that everything will come to you eventually. Become a detective of the right moment; sniff out the spirit of the times, the trends that will carry you to power.",
    principle: "Timing is everything in power dynamics. The same action taken at different times can have completely different results. Learn to recognize when the moment is right.",
    historicalExample: "Warren Buffett's investment success comes largely from his patience—waiting for the right opportunities and not being pressured into premature action. His timing has made him one of the world's richest men.",
    keyPoints: ["Patience demonstrates control", "Wait for the right moment", "Read the zeitgeist", "Timing trumps effort"],
    category: "Strategy",
    icon: "clock"
  },
  {
    id: 36,
    title: "Disdain Things You Cannot Have: Ignoring Them Is the Best Revenge",
    shortDescription: "By acknowledging a petty problem you give it existence and credibility. The more attention you pay an enemy, the stronger you make him.",
    fullDescription: "By acknowledging a petty problem you give it existence and credibility. The more attention you pay an enemy, the stronger you make him; and a small mistake is often made worse and more visible when you try to fix it. It is sometimes best to leave things alone.",
    principle: "Attention gives power to people and problems. By ignoring what you cannot control or change, you deny it the energy it needs to affect you. Focus your attention only on what serves your purposes.",
    historicalExample: "When critics attacked his work, Pablo Picasso rarely responded directly. His silence and continued innovation spoke louder than any defense could have, and eventually his critics looked petty and irrelevant.",
    keyPoints: ["Ignore what you cannot control", "Don't give power to enemies", "Silence can be the strongest response", "Focus energy on what matters"],
    category: "Defense",
    icon: "eye-slash"
  },
  {
    id: 37,
    title: "Create Compelling Spectacles",
    shortDescription: "Striking imagery and grand symbolic gestures create the aura of power—everyone responds to them. Stage spectacles for those around you.",
    fullDescription: "Striking imagery and grand symbolic gestures create the aura of power—everyone responds to them. Stage spectacles for those around you, then, full of arresting visuals and radiant symbols that heighten your presence. Dazzled by appearances, no one will notice what you are really doing.",
    principle: "Humans are visual creatures who respond more to what they see than what they hear. Spectacular presentations can overwhelm rational thinking and create lasting impressions.",
    historicalExample: "Steve Jobs turned Apple product launches into theatrical events with carefully choreographed presentations. These spectacles created excitement and desire that went far beyond the actual features of the products.",
    keyPoints: ["Visual impact trumps logic", "Create memorable experiences", "Use symbolism effectively", "Distract from your true actions"],
    category: "Influence",
    icon: "theater-masks"
  },
  {
    id: 38,
    title: "Think as You Like but Behave Like Others",
    shortDescription: "If you make a show of going against the times, flaunting your unconventional ideas and unorthodox ways, people will think that you only want attention.",
    fullDescription: "If you make a show of going against the times, flaunting your unconventional ideas and unorthodox ways, people will think that you only want attention and that you look down upon them. They will find a way to punish you for making them feel inferior. It is far safer to blend in and nurture the common touch.",
    principle: "Social conformity on the surface allows you to operate freely underneath. Blend in with the crowd while maintaining your unique perspective privately.",
    historicalExample: "Galileo's public challenges to church doctrine led to his persecution, while other scientists who kept their revolutionary ideas private but conformed publicly were able to continue their work unmolested.",
    keyPoints: ["Conform outwardly while thinking freely", "Don't threaten others' beliefs openly", "Blend in to avoid persecution", "Save your energy for what matters"],
    category: "Defense",
    icon: "mask"
  },
  {
    id: 39,
    title: "Stir Up Waters to Catch Fish",
    shortDescription: "Anger and emotion are strategically counterproductive. You must always stay calm and objective. But if you can make your enemies angry while staying calm yourself, you gain a decided advantage.",
    fullDescription: "Anger and emotion are strategically counterproductive. You must always stay calm and objective. But if you can make your enemies angry while staying calm yourself, you gain a decided advantage. Put your enemies off-balance: Find the chink in their vanity through which you can rattle them.",
    principle: "Emotional people make poor decisions. By provoking others while maintaining your own composure, you force them into reactive behavior that you can predict and exploit.",
    historicalExample: "Muhammad Ali was a master at psychological warfare, provoking opponents with taunts and predictions that made them fight emotionally instead of strategically, often leading to their defeat.",
    keyPoints: ["Stay calm under pressure", "Provoke enemies strategically", "Emotional opponents make mistakes", "Use their reactions against them"],
    category: "Strategy",
    icon: "wave"
  },
  {
    id: 40,
    title: "Despise the Free Lunch",
    shortDescription: "What is offered for free is dangerous—it usually involves either a trick or a hidden obligation. What has worth is worth paying for.",
    fullDescription: "What is offered for free is dangerous—it usually involves either a trick or a hidden obligation. What has worth is worth paying for. By paying your own way you stay clear of gratitude, guilt, and deceit. It is also often wise to pay the full price—there is no cutting corners with excellence.",
    principle: "Free things come with hidden costs—often your independence or your obligation to the giver. Paying fairly maintains your freedom and self-respect.",
    historicalExample: "The Trojan Horse appeared to be a free gift but carried hidden enemies. Similarly, many business deals that seem too good to be true usually involve hidden obligations or costs.",
    keyPoints: ["Nothing is truly free", "Independence has value", "Avoid hidden obligations", "Pay fairly for quality"],
    category: "Defense",
    icon: "gift"
  },
  {
    id: 41,
    title: "Avoid Stepping into a Great Man's Shoes",
    shortDescription: "What happens first always appears better and more original than what comes after. If you succeed a great man or have a famous parent, you will have to accomplish double their achievements to outshine them.",
    fullDescription: "What happens first always appears better and more original than what comes after. If you succeed a great man or have a famous parent, you will have to accomplish double their achievements to outshine them. Do not get lost in their shadow, or stuck in a past not of your own making: Establish your own name and identity by changing course.",
    principle: "Following in someone else's footsteps means you'll always be compared to them. Create your own path to avoid being judged against their legacy.",
    historicalExample: "When John F. Kennedy Jr. chose to go into journalism rather than politics, he avoided the impossible task of living up to his father's presidential legacy and created his own identity and success.",
    keyPoints: ["Comparisons are inevitable", "Create your own path", "Avoid living in shadows", "Change direction to establish identity"],
    category: "Strategy",
    icon: "footsteps"
  },
  {
    id: 42,
    title: "Strike the Shepherd and the Sheep Will Scatter",
    shortDescription: "Trouble can often be traced to a single strong individual—the stirrer, the arrogant underling, the poisoner of goodwill. If you allow such people room to operate, others will succumb to their influence.",
    fullDescription: "Trouble can often be traced to a single strong individual—the stirrer, the arrogant underling, the poisoner of goodwill. If you allow such people room to operate, others will succumb to their influence. Do not wait for the troubles they cause to multiply, do not try to negotiate with them—they are irredeemable. Neutralize their influence by isolating or banishing them.",
    principle: "Groups usually follow strong personalities. By removing the leader or main influencer, you can often solve multiple problems at once. Deal with the source, not the symptoms.",
    historicalExample: "When corporate teams have persistent problems, it often traces back to one toxic individual whose negative influence spreads. Removing that person frequently transforms the entire team dynamic.",
    keyPoints: ["Identify the real source of problems", "Remove toxic influences quickly", "Groups follow strong personalities", "Deal with causes not symptoms"],
    category: "Strategy",
    icon: "crosshairs"
  },
  {
    id: 43,
    title: "Work on the Hearts and Minds of Others",
    shortDescription: "Coercion creates a reaction that will eventually work against you. You must seduce others into wanting to move in your direction.",
    fullDescription: "Coercion creates a reaction that will eventually work against you. You must seduce others into wanting to move in your direction. A person you have seduced becomes your loyal pawn. And the way to seduce others is to operate on their individual psychologies and weaknesses.",
    principle: "Willing cooperation is more powerful and lasting than forced compliance. When people want to help you, they'll go beyond what you could ever force them to do.",
    historicalExample: "Franklin D. Roosevelt's fireside chats seduced the American public into supporting his policies through emotional connection rather than political force, creating unprecedented popular backing for his presidency.",
    keyPoints: ["Seduction beats coercion", "Appeal to individual psychology", "Create willing allies", "Understand personal motivations"],
    category: "Influence",
    icon: "heart"
  },
  {
    id: 44,
    title: "Disarm and Infuriate with the Mirror Effect",
    shortDescription: "The mirror reflects reality, but it is also the perfect tool for deception: When you mirror your enemies, doing exactly as they do, they cannot figure out your strategy.",
    fullDescription: "The mirror reflects reality, but it is also the perfect tool for deception: When you mirror your enemies, doing exactly as they do, they cannot figure out your strategy. The Mirror Effect mocks and humiliates them, making them overreact. By holding up a mirror to their psyches, you seduce them with the illusion that you share their values.",
    principle: "Mirroring confuses opponents and makes them reveal their true nature. It's also a powerful tool for building rapport and exposing others' weaknesses.",
    historicalExample: "During negotiations, skilled diplomats often mirror their counterparts' body language and speaking style, creating unconscious rapport while gathering information about their true positions.",
    keyPoints: ["Mirroring creates confusion", "Reflect back their energy", "Expose their true nature", "Build unconscious rapport"],
    category: "Strategy",
    icon: "mirror"
  },
  {
    id: 45,
    title: "Preach the Need for Change, but Never Reform Too Much at Once",
    shortDescription: "Everyone understands the need for change in the abstract, but on the day-to-day level people are creatures of habit. Too much innovation is traumatic.",
    fullDescription: "Everyone understands the need for change in the abstract, but on the day-to-day level people are creatures of habit. Too much innovation is traumatic, and will lead to revolt. If you are new to a position of power, or an outsider trying to build a power base, make a show of respecting the old way of doing things.",
    principle: "Change must be gradual to be accepted. People fear radical transformation even when they intellectually understand its necessity. Respect traditions while slowly introducing improvements.",
    historicalExample: "When Steve Jobs returned to Apple, he didn't immediately overhaul everything. He gradually introduced changes while maintaining some familiar elements, making the transformation more acceptable to employees and customers.",
    keyPoints: ["Change gradually not radically", "Respect existing traditions", "People fear rapid transformation", "Show respect while improving"],
    category: "Strategy",
    icon: "seedling"
  },
  {
    id: 46,
    title: "Never Appear Too Perfect",
    shortDescription: "Appearing better than others is always dangerous, but most dangerous of all is to appear to have no faults or weaknesses. Envy creates silent enemies.",
    fullDescription: "Appearing better than others is always dangerous, but most dangerous of all is to appear to have no faults or weaknesses. Envy creates silent enemies. It is smart to occasionally display defects, and admit to harmless vices, in order to deflect envy and appear more human and approachable.",
    principle: "Perfection threatens others and creates resentment. Strategic vulnerability makes you more relatable and less threatening while still maintaining your essential power.",
    historicalExample: "Winston Churchill's well-known fondness for cigars and whiskey made him seem more human and relatable, deflecting potential envy over his intelligence and leadership abilities.",
    keyPoints: ["Perfection creates enemies", "Show harmless flaws", "Appear human and relatable", "Deflect envy strategically"],
    category: "Defense",
    icon: "smile"
  },
  {
    id: 47,
    title: "Do Not Go Past the Mark You Aimed For; In Victory, Learn When to Stop",
    shortDescription: "The moment of victory is often the moment of greatest peril. In the heat of victory, arrogance and overconfidence can push you past the goal you had aimed for.",
    fullDescription: "The moment of victory is often the moment of greatest peril. In the heat of victory, arrogance and overconfidence can push you past the goal you had aimed for, and by going too far, you make more enemies than you defeat. Do not allow success to go to your head. There is no substitute for strategy and careful planning.",
    principle: "Success can be intoxicating and lead to overreach. Know when you've achieved your objective and resist the temptation to press your advantage too far.",
    historicalExample: "Napoleon's invasion of Russia was the result of not knowing when to stop. After conquering most of Europe, his overreach led to his ultimate downfall and exile.",
    keyPoints: ["Victory can lead to overconfidence", "Know when to stop", "Success creates new enemies", "Strategy must continue in victory"],
    category: "Strategy",
    icon: "target"
  },
  {
    id: 48,
    title: "Assume Formlessness",
    shortDescription: "By taking a shape, by having a visible plan, you open yourself to attack. Instead of taking a form for your enemy to grasp, keep yourself adaptable and on the move.",
    fullDescription: "By taking a shape, by having a visible plan, you open yourself to attack. Instead of taking a form for your enemy to grasp, keep yourself adaptable and on the move. Accept the fact that nothing is certain and no law is fixed. The best way to protect yourself is to be as fluid and formless as water.",
    principle: "Rigid structures can be broken, but formless things cannot be grasped or attacked. Maintain flexibility and adaptability as your greatest strengths.",
    historicalExample: "Guerrilla warfare succeeds because it has no fixed form for conventional armies to attack. The fighters blend with the population and adapt their tactics constantly, making them nearly impossible to defeat through traditional means.",
    keyPoints: ["Avoid rigid structures", "Stay adaptable and flexible", "Formless things can't be attacked", "Embrace uncertainty and change"],
    category: "Defense",
    icon: "water"
  }
];

export const lawsData: Law[] = rawLawsData.map(law => ensureCompleteData(law));
